# Generated by Django 4.1 on 2022-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured_img'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/main_img'),
        ),
    ]
