# Generated by Django 4.1 on 2022-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_post_featured_img_post_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
