# Generated by Django 4.1 on 2022-08-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='codes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hex',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
