# Generated by Django 4.1 on 2022-08-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_post_codes_post_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
