# Generated by Django 4.1 on 2022-08-23 11:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_post_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='codes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
