# Generated by Django 4.1 on 2022-08-24 11:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_post_body_alter_post_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=255)),
                ('asking', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_text', tinymce.models.HTMLField()),
            ],
        ),
    ]
