# Generated by Django 4.1 on 2022-08-24 12:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_aboutus_contactus_licence_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', tinymce.models.HTMLField(blank=True, null=True)),
                ('privacy_policy', tinymce.models.HTMLField(blank=True, null=True)),
                ('about_us', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Aboutus',
        ),
        migrations.DeleteModel(
            name='licence',
        ),
        migrations.DeleteModel(
            name='privacy_policy',
        ),
    ]
