# Generated by Django 4.1 on 2022-08-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_aboutus_licence_privacy_policy_delete_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
        migrations.DeleteModel(
            name='licence',
        ),
        migrations.DeleteModel(
            name='Privacy_policy',
        ),
    ]
