# Generated by Django 4.1 on 2022-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_delete_aboutus_delete_licence_delete_privacy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured',
        ),
        migrations.AddField(
            model_name='category',
            name='bootstrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='dark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='hcj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='tailwind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='with_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='without_code',
            field=models.BooleanField(default=False),
        ),
    ]
