# Generated by Django 4.1 on 2022-09-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_category_featured_category_bootstrap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.post')),
            ],
        ),
    ]
