# Generated by Django 4.1 on 2022-09-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='with_code',
        ),
        migrations.AddField(
            model_name='post',
            name='with_code',
            field=models.BooleanField(default=False),
        ),
    ]
