# Generated by Django 4.1 on 2022-09-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_remove_category_bootstrap_remove_category_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hex',
        ),
    ]
