# Generated by Django 4.1 on 2022-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_remove_post_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkTab',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
