# Generated by Django 4.1 on 2022-09-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_post_linktab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
