# Generated by Django 4.1 on 2022-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_delete_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/video'),
        ),
    ]
