# Generated by Django 2.2.13 on 2023-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_auto_20230217_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
