# Generated by Django 2.2.13 on 2023-02-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20230217_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(blank=True, null=True, upload_to='blog/video')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sale_price',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
