# Generated by Django 2.2.13 on 2023-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20230218_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header_img',
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='blog/video'),
        ),
    ]
